name: EpicBlocker
version: '1.0.0-Bukkit'
main: cl.staff.epicblocker.EpicBlocker
author: Not_staff
api-version: '1.16'

commands:
  eb reload:
    description: Reload the config.yml configuration

permissions:
  epicblocker.reload:
    description: It gives you the permission to execute the /eb reload command.
    default: false